version: '3'
services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
    networks:
      - awx_network

  redis:
    image: redis:alpine
    networks:
      - awx_network

  awx:
    image: ansible/awx:latest
    hostname: awx
    ports:
      - "80:8052"
    depends_on:
      - redis
      - postgres
    environment:
      AWX_ADMIN_USER: admin
      AWX_ADMIN_PASSWORD: admin_password
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      REDIS_HOST: redis
    volumes:
      - awx_projects:/var/lib/awx/projects
    networks:
      - awx_network

volumes:
  postgres_data:
  awx_projects:

networks:
  awx_network:
    driver: bridge