---
- name: Install Podman
  hosts: all
  become: yes

  tasks:
    - name: Install Podman on RedHat
      when: ansible_facts['os_family'] == 'RedHat'
      block:
        - name: Enable EPEL repository
          dnf:
            name: epel-release
            state: present

        - name: Install Podman
          dnf:
            name: podman
            state: latest

    - name: Install Podman on Debian
      when: ansible_facts['os_family'] == 'Debian'
      block:
        - name: Add Kubic repository
          apt_repository:
            repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /
            filename: podman
            state: present
            update_cache: yes

        - name: Install Podman
          apt:
            name: podman
            state: latest
            update_cache: yes

    - name: Verify Podman installation
      command: podman --version
      register: podman_version
      changed_when: false

    - name: Show installed version
      debug:
        msg: "Podman {{ podman_version.stdout }} installed"