---
- name: Deploy Podman on target hosts
  hosts: all
  become: yes
  tasks:
    - name: Ensure Podman is installed
      package:
        name: podman
        state: present

    - name: Verify Podman installation
      command: podman --version
      register: podman_version
      changed_when: false

    - name: Show Podman version
      debug:
        msg: "Podman version installed: {{ podman_version.stdout }}"